### PR TITLE
Delivery for Distance And Direction Addin - #684

### PR DESCRIPTION
**Pull request by sumitzarkar**
Implemented following points:
1. Removing: ArcMapAddinDistanceAndDirection project/dll
2. Removing: DistanceAndDirectionLibrary project/dll
3. Refactoring the Pro project to remove dependencies on former DistanceAndDirectionLibrary 
    a. remove view inheritance
    b. remove no-longer-needed classes (super/abstract classes)
    c. remove mediator/dispatcher (ex: convert to RelayCommands) 
    d. use Pro styling for Dark Mode support
5. As part of this if you notice any hard-coded UI strings that should be converted to Resources (for I18n) please convert these to resources

In Addition to this, we have also commited the code for UAT feedback mentioned in https://github.com/Esri/distance-direction-addin-dotnet/issues/684#issuecomment-584437025

### CODE REVIEW

**Comment by csmoore** [comment]
Thanks for the hard work on this. @oscarvilla1 and I tested yesterday and didn't notice and issues.

I noticed a few minor remaining unused variables that I will probably do a PR for into your branch.

Speaking of PRs, I should discuss with the team where (which branch) the changes you made should go (they may not get merged into dev, but another long-lived branch - like https://github.com/Esri/distance-direction-addin-dotnet/tree/dev-Pro2.6 ) - so we will leave this PR open until we make a decision.

But I did want to let you know that things look and test as expected and nice job. Thanks

**Comment by OscarVilla1** [comment]
Awesome, thank you
________________________________

**Comment by csmoore** [comment]
Opened alternate PR #686 - so we could just switch the head branch we are merging into (branch: Pro2.6 vs. dev). Feel free to move any discussion to that PR and sorry for any confusion.

**Comment by csmoore** [comment]
Closing unmerged to merge into different head branch in PR #686

**Pull request closed without merging**
