### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by jmccausland**
Added tests for ArcMap and Pro
Updated readme

### CODE REVIEW

**Comment by jmccausland** [comment]
@dhagens please review and merge

**Comment by dhagens** [comment]
@jmccausland, add Esri headers to test files.

**Comment by dhagens** [comment]
@jmccausland, you can add the following instead of using in every method:

//Use ClassInitialize to run code before running the first test in the class
        [ClassInitialize()]
        [TestCategory("ArcMapAddin")]
        public static void MyClassInitialize(TestContext testContext)
        {
            bool blnBoundToRuntime = ESRI.ArcGIS.RuntimeManager.Bind(ESRI.ArcGIS.ProductCode.EngineOrDesktop);
            Assert.IsTrue(blnBoundToRuntime, "Not bound to runtime");

            IAoInitialize aoInitialize = new AoInitializeClass();
            aoInitialize.Initialize(esriLicenseProductCode.esriLicenseProductCodeAdvanced); 
        }

**Comment by jmccausland** [comment]
@dhagens updated

**Comment by csmoore** [comment]
Does this addin really require an Advanced License (esriLicenseProductCodeAdvanced) ?  If so may want to highlight in [Readme](https://github.com/Esri/distance-direction-addin-dotnet#arcgis-for-desktop-users)

**Comment by jmccausland** [comment]
I was wondering when someone was going to say something about that

**Comment by dhagens** [comment]
Per @csmoore suggestion, try using a lower license level to initialize.

aoInitialize.Initialize(esriLicenseProductCode.esriLicenseProductCodeBasic);

**Comment by jmccausland** [comment]
@dhagens already did before you commented

**Comment by dhagens** [comment]
Already deleted before you commented.  :)

**Pull request merged**
