### PR TITLE
Clear graphics when Circle/Distance field cleared completely

### PR DESCRIPTION
**Pull request by rjones0**
Please review.

### CODE REVIEW

**Comment by rjones0** [comment]
@kgonzago thanks for the merge. A question on tests - on conf call yesterday it was mentioned that I should write a test for each fix. How should I approach writing a test for this since the outcome we want is that graphics are cleared from ArcMap? Should I be launching ArcMap and simulating input as part of the test?

**Comment by kgonzago** [comment]
@rjones0 it will be a challenge to create a unit test for clearing graphics for example. In that situation, perhaps a unit test to check if D&D graphics were removed from the graphics container. Thoughts?

**Comment by rjones0** [comment]
@kgonzago would it be worth capturing the issues that cannot be checked via automated testing by adding a label to the issue? This way, when each release is being prepared it should be possible to generate a list of issues and if each issue contains full steps to recreate and expected result, the overall task should not be too difficult to execute.

**Comment by kgonzago** [comment]
@rjones0 agreed on your label suggestion.

**Comment by rjones0** [comment]
@kgonzago Also wondered whether it might be worth including the issue number within the test name in order to link the two quickly, i.e. I've just added tests CircleViewModel_ThrowsException5 to CircleViewModel_ThrowsException11 for #198 - perhaps they could be named e.g. CircleViewModel_ThrowsException5_198?

**Comment by rjones0** [comment]
@kgonzago on your previous test suggestion i.e. check if D&D graphics were removed from the graphics container - the creation of the graphic in the first place is tightly coupled to presence of a valid reference to ArcMap (see AddGraphicToMap method in TabBaseViewModel.cs), which I think makes the set up of the test within the current test structure impossible without refactoring of that method. It should be a 5 minute or less manual test or if the manual testing were proving onerous perhaps we could look at something like: https://www.autoitscript.com/site/autoit/

**Pull request merged**
