### PR TITLE
updated the labels

### PR DESCRIPTION
**Pull request by topowright**
Updated label colors, shadows , some that were base don a line, but still stacking. Took away the stacking portion. Addressed mutiple issues in the sprint, but #544 is one of them.

### CODE REVIEW

**Comment by ACueva** [comment]
IMO, this is still hard to read.  @dfoll @topowright thoughts?

**Comment by dfoll** [comment]
I think we have just made it hard to read on lighter backgrounds now, we may need to spend more time on an elegant way to completely resolve the problem

**Comment by topowright** [comment]
trying another color of gray that should work better

**Comment by topowright** [comment]
image

image

**Comment by ACueva** [comment]
@topowright @dfoll for the unit of measurement, should we stick with a space in between or have the value be right next to the value? I'm inclined to go with the second option, unless there's a reason not to. 
i.e.: Meters

```
1000 m
29 °
```
or

```
1000m
29°
```

**Comment by ACueva** [comment]
@topowright Let me know what you think of the readability of this code:

```
var unit = $feature.DistUnit;

/* This converts labels to the abbreviated unit of measurement */
var unitMeasurement = When(
unit == 'Feet','ft', 
unit == 'Kilometers','km',
unit == 'Meters','m',
unit == 'Miles', 'mi',
unit == 'Nautical Miles','n.m.',
unit == 'yards');

Text($feature.Distance, '####') + unitMeasurement
```

**Comment by csmoore** [comment]
I would also agree that the labels above are hard to read.

What the military symbols use for foreground (black) + shadow (white) + thickness seems to work well on both light/dark backgrounds - ex:

image

image

**Comment by dfoll** [comment]
i like @csmoore approach, has this actually been tried yet?

**Comment by topowright** [comment]
@ACueva here is the updated changes. 

@dfoll we had tried @csmoore and @lfunkhouser preferred shadows instead of halos based on the idea that some backgrounds make them look like bubble letters. 

We are ready to move forward and merge this pull request when @ACueva says it is a go.

**Comment by ACueva** [comment]
@topowright I'm not seeing the updated arcade expressions in this branch.  Is there a different one I should be testing against?

**Comment by csmoore** [comment]
Here is how the labels currently look after this PR:

image

**Pull request merged**
