### PR TITLE
Change Save-As format

### PR DESCRIPTION
**Pull request by kgonzago**
This addresses a new request from @topowright and @dfoll for issue #385 on how the `Save-As` should work. The new `Save-As` dialog in Pro now looks like this:

image

### CODE REVIEW

**Comment by ACueva** [comment]
@kgonzago Is it possible to show the highlighted part as a "Shapefile"?  There's nothing that tells me as a user what I'll be saving my file as a shapefile.



Expected behavior would be:
If you are in a .gdb, then the pulldown showing "Feature Classes (All Types)" would be fine.
If I'm not in a .gdb, I'd expect the pulldown to say "Shapefile".

**Comment by csmoore** [comment]
Looks like the closest filter that the Pro SaveItemDialog provides might be "ItemFilters.composite_addToMap" (anything that can be added to the map) but that is going to give you some things you don't want

image

**Comment by BobBooth** [comment]
The "Feature Class to Feature Class" tool in Pro seems not to indicate type - it just says "feature class". If you save in a file geodatabase, you get a feature class, and if you save in a folder, you get a shapefile.
image

**Comment by ACueva** [comment]
Based on this feedback, I'm going to merge.  Our behavior is consistent with the ArcGIS Pro behavior.

**Pull request merged**
